version: "3"

tasks:
  dev:
    desc: Lancer le serveur de développement
    cmds:
      - pnpm dev

  create-recettes:
    desc: Générer les recettes et builder le projet
    cmds:
      - pnpm generate:recettes

  push:
    desc: Préparer le code et pousser
    cmds:
      - pnpm format
      - pnpm lint:fix
      - pnpm build
      - git add .
      - git commit -m "task push"
      - git push origin main
